In [12]:
import pandas as pd

matches = pd.read_csv(
    "../data/raw/matches.csv"
)

matches.head()

,match_id,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,2,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,3,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,4,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,5,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [13]:
matches.duplicated().sum()

np.int64(0)

In [14]:
matches.isnull().sum()

match_id       0
date           0
home_team      0
away_team      0
home_score    72
away_score    72
tournament     0
city           0
country        0
neutral        0
dtype: int64

In [15]:
matches["home_team"] = (
matches["home_team"]
.str.strip()
.str.title()
)

matches["away_team"] = (
matches["away_team"]
.str.strip()
.str.title()
)

In [16]:
matches["date"] = pd.to_datetime(
matches["date"]
)

In [17]:
matches["year"] = (
matches["date"]
.dt.year
)

In [18]:
matches["month"] = (
matches["date"]
.dt.month
)

In [21]:
matches.to_csv(
"../data/processed/matches_clean.csv",
index=False
)

In [22]:
matches.shape

(49287, 12)

In [23]:
matches.to_csv(
    "../data/processed/matches_clean.csv",
    index=False
)

In [24]:
matches.head()

,match_id,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,year,month
0,1,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False,1872,11
1,2,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False,1873,3
2,3,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False,1874,3
3,4,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False,1875,3
4,5,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False,1876,3