In [20]:
import pandas as pd
import numpy as np

In [25]:
matches = pd.read_csv(
"../data/processed/model_input.csv"
)

In [26]:
matches.head()

,match_id,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,year,month,goal_diff,target,attack_strength,total_goals,avg_goals
0,5,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False,1876,3,3.0,2,2.2,3.0,3.2
1,6,1876-03-25,Scotland,Wales,4.0,0.0,Friendly,Glasgow,Scotland,False,1876,3,4.0,2,3.0,4.0,4.0
2,7,1877-03-03,England,Scotland,1.0,3.0,Friendly,London,England,False,1877,3,-2.0,0,2.4,4.0,3.6
3,8,1877-03-05,Wales,Scotland,0.0,2.0,Friendly,Wrexham,Wales,False,1877,3,-2.0,0,2.0,2.0,3.4
4,9,1878-03-02,Scotland,England,7.0,2.0,Friendly,Glasgow,Scotland,False,1878,3,5.0,2,3.0,9.0,4.4

In [27]:
matches[
"home_defense_avg"
] = (

matches[
"away_score"
]

.rolling(5)

.mean()

)

In [28]:
matches[
"away_defense_avg"
] = (

matches[
"home_score"
]

.rolling(5)

.mean()

)

In [29]:
matches[
[
"home_defense_avg",

"away_defense_avg"
]
].head()

   home_defense_avg  away_defense_avg
0               NaN               NaN
1               NaN               NaN
2               NaN               NaN
3               NaN               NaN
4               1.4               3.0

In [31]:
matches["away_form"] = (
    matches["away_score"] >
    matches["home_score"]
).astype(int).rolling(5).mean()

In [32]:
matches[
"home_win"
] = (

matches[
"home_score"
]

>

matches[
"away_score"

]

).astype(
int
)

In [33]:
matches[
"win_streak"
] = (

matches[
"home_win"
]

.rolling(
5
)

.sum()

)

In [34]:
matches[
"home_loss"
] = (

matches[
"home_score"
]

<

matches[
"away_score"

]

).astype(
int
)

In [35]:
matches[
"loss_streak"
] = (

matches[
"home_loss"
]

.rolling(
5
)

.sum()

)

In [36]:
matches.columns

Index(['match_id', 'date', 'home_team', 'away_team', 'home_score',
       'away_score', 'tournament', 'city', 'country', 'neutral', 'year',
       'month', 'goal_diff', 'target', 'attack_strength', 'total_goals',
       'avg_goals', 'home_defense_avg', 'away_defense_avg', 'away_form',
       'home_win', 'win_streak', 'home_loss', 'loss_streak'],
      dtype='str')

In [37]:
matches["home_attack_avg"] = (
    matches[
        "home_score"
    ]
    .rolling(5)
    .mean()
)

In [38]:
matches[
[
"home_score",
"home_attack_avg"
]
].head(10)

   home_score  home_attack_avg
0         3.0              NaN
1         4.0              NaN
2         1.0              NaN
3         0.0              NaN
4         7.0              3.0
5         9.0              4.2
6         2.0              3.8
7         5.0              4.6
8         0.0              4.6
9         5.0              4.2

In [39]:
matches["away_attack_avg"] = (
    matches[
        "away_score"
    ]
    .rolling(5)
    .mean()
)

In [40]:
matches[
[
"away_score",
"away_attack_avg"
]
].head(10)

   away_score  away_attack_avg
0         0.0              NaN
1         0.0              NaN
2         3.0              NaN
3         2.0              NaN
4         2.0              1.4
5         0.0              1.4
6         1.0              1.6
7         4.0              1.8
8         3.0              2.0
9         4.0              2.4

In [41]:
matches["home_form"] = (
    (
        matches[
            "home_score"
        ]
        >
        matches[
            "away_score"
        ]
    )
    .astype(int)
    .rolling(5)
    .mean()
)

In [42]:
matches[
[
"home_form"
]
].head(10)

   home_form
0        NaN
1        NaN
2        NaN
3        NaN
4        0.6
5        0.6
6        0.6
7        0.8
8        0.8
9        0.8

In [43]:
print(
matches.columns
)

Index(['match_id', 'date', 'home_team', 'away_team', 'home_score',
       'away_score', 'tournament', 'city', 'country', 'neutral', 'year',
       'month', 'goal_diff', 'target', 'attack_strength', 'total_goals',
       'avg_goals', 'home_defense_avg', 'away_defense_avg', 'away_form',
       'home_win', 'win_streak', 'home_loss', 'loss_streak', 'home_attack_avg',
       'away_attack_avg', 'home_form'],
      dtype='str')

In [44]:
matches = matches.replace(
[np.inf,-np.inf],
np.nan
)

In [45]:
matches = matches.dropna(
subset=[

"home_attack_avg",

"away_attack_avg",

"home_defense_avg",

"away_defense_avg",

"home_form",

"away_form",

"win_streak",

"loss_streak",

"target"

]
)

In [46]:
matches.isnull().sum()

match_id            0
date                0
home_team           0
away_team           0
home_score          0
away_score          0
tournament          0
city                0
country             0
neutral             0
year                0
month               0
goal_diff           0
target              0
attack_strength     0
total_goals         0
avg_goals           0
home_defense_avg    0
away_defense_avg    0
away_form           0
home_win            0
win_streak          0
home_loss           0
loss_streak         0
home_attack_avg     0
away_attack_avg     0
home_form           0
dtype: int64

In [47]:
matches.to_csv(

"../data/processed/advanced_model_input.csv",

index=False

)